from __future__ import annotations

from typing import Any


CURRICULUM_SOURCES: list[dict[str, str]] = [
    {
        "id": "edb-kla-overview-2526",
        "title": "EDB Subjects under the Eight Key Learning Areas (2025/26)",
        "url": "https://www.edb.gov.hk/en/curriculum-development/kla/overview.html",
        "note": "P1-S6 official subject list and implementation notes.",
    },
    {
        "id": "edb-kindergarten-overview",
        "title": "EDB Overview of Kindergarten Education in Hong Kong",
        "url": "https://www.edb.gov.hk/en/edu-system/preprimary-kindergarten/overview/",
        "note": "K1-K3 developmental objectives and six learning areas.",
    },
    {
        "id": "edb-primary-guide-2024",
        "title": "EDB Primary Education Curriculum Guide (2024)",
        "url": "https://www.edb.gov.hk/en/curriculum-development/major-level-of-edu/primary/curriculum-documents/Primary_Education_Curriculum_Guide.html",
        "note": "Primary curriculum renewal, seven learning goals, and school-based planning.",
    },
    {
        "id": "edb-secondary-guide-2017",
        "title": "EDB Secondary Education Curriculum Guide (2017)",
        "url": "https://www.edb.gov.hk/en/curriculum-development/major-level-of-edu/secondary/CG_documents.html",
        "note": "Junior secondary KLAs and senior secondary curriculum framework.",
    },
    {
        "id": "edb-csd-docs",
        "title": "EDB Citizenship and Social Development Curriculum and Assessment Guide",
        "url": "https://www.edb.gov.hk/attachment/en/curriculum-development/renewal/CS/CS_CAG_S4-6_Eng_2021.pdf",
        "note": "Senior secondary CSD themes, learning aims, assessment, and Mainland study tour connection.",
    },
    {
        "id": "edb-chinese-docs",
        "title": "EDB Chinese Language Education Curriculum Documents",
        "url": "https://www.edb.gov.hk/en/curriculum-development/kla/chi-edu/curriculum-documents.html",
        "note": "Chinese Language, Putonghua, and Chinese Literature curriculum documents.",
    },
    {
        "id": "edb-english-docs",
        "title": "EDB English Language Education Curriculum Documents",
        "url": "https://www.edb.gov.hk/elecg",
        "note": "English Language and Literature in English curriculum documents.",
    },
    {
        "id": "edb-mathematics-docs",
        "title": "EDB Mathematics Education",
        "url": "https://www.edb.gov.hk/en/curriculum-development/kla/ma/index.html",
        "note": "Mathematics Education KLA direction and curriculum documents.",
    },
    {
        "id": "edb-science-docs",
        "title": "EDB Science Education Curriculum Documents",
        "url": "https://www.edb.gov.hk/en/curriculum-development/kla/science-edu/curriculum-documents.html",
        "note": "Primary Science, S1-S3 Science, and S4-S6 science subjects.",
    },
    {
        "id": "edb-technology-docs",
        "title": "EDB Technology Education Curriculum Documents",
        "url": "https://www.edb.gov.hk/en/curriculum-development/kla/technology-edu/curriculum-doc/index.html",
        "note": "Technology Education KLA, coding education, AI module, and S4-S6 technology subjects.",
    },
    {
        "id": "edb-pshe-docs",
        "title": "EDB Personal, Social and Humanities Education Curriculum Documents",
        "url": "https://www.edb.gov.hk/en/curriculum-development/kla/pshe/curriculum-documents.html",
        "note": "PSHE KLA, Chinese History, CES, Geography, History, Economics, and related subjects.",
    },
    {
        "id": "edb-arts-docs",
        "title": "EDB Arts Education Curriculum Documents",
        "url": "https://www.edb.gov.hk/en/curriculum-development/kla/arts-edu/curriculum-docs/index.html",
        "note": "Music and Visual Arts curriculum documents.",
    },
    {
        "id": "edb-pe-docs",
        "title": "EDB Physical Education Curriculum Documents",
        "url": "https://www.edb.gov.hk/en/curriculum-development/kla/pe/curriculum-doc/index.html",
        "note": "P1-S6 PE KLA guide and senior secondary PE guide.",
    },
]

CURRICULUM_STAGES: list[dict[str, str]] = [
    {
        "id": "kg",
        "label": "K1-K3",
        "caption": "Kindergarten",
        "learning_goal": "五大發展目標，透過遊戲、生活主題及綜合學習建立學習興趣。",
    },
    {
        "id": "p1-p6",
        "label": "P1-P6",
        "caption": "Primary",
        "learning_goal": "八個學習領域打底，並逐步以小學科學及小學人文取代常識科。",
    },
    {
        "id": "s1-s3",
        "label": "S1-S3",
        "caption": "Junior Secondary",
        "learning_goal": "八個學習領域連接高中選科，中史為初中獨立必修科。",
    },
    {
        "id": "s4-s6",
        "label": "S4-S6",
        "caption": "Senior Secondary",
        "learning_goal": "核心、選修、應用學習、其他語言及其他學習經歷並行。",
    },
]

CURRICULUM_SUBJECTS: list[dict[str, Any]] = [
    {
        "id": "kg-physical-fitness-health",
        "name": "Physical Fitness and Health",
        "display_name_zh": "體能與健康",
        "kla_id": "kindergarten",
        "kla_name": "Kindergarten Learning Areas",
        "stage_ids": ["kg"],
        "grades": ["K1", "K2", "K3"],
        "strands": ["gross motor", "health habits", "safety awareness"],
        "app_use": "portfolio evidence and whole-child growth tags",
        "source_ids": ["edb-kindergarten-overview"],
    },
    {
        "id": "kg-language",
        "name": "Language",
        "display_name_zh": "語文",
        "kla_id": "kindergarten",
        "kla_name": "Kindergarten Learning Areas",
        "stage_ids": ["kg"],
        "grades": ["K1", "K2", "K3"],
        "strands": ["listening", "speaking", "early literacy"],
        "app_use": "portfolio language evidence and parent observation prompts",
        "source_ids": ["edb-kindergarten-overview"],
    },
    {
        "id": "kg-early-childhood-mathematics",
        "name": "Early Childhood Mathematics",
        "display_name_zh": "幼兒數學",
        "kla_id": "kindergarten",
        "kla_name": "Kindergarten Learning Areas",
        "stage_ids": ["kg"],
        "grades": ["K1", "K2", "K3"],
        "strands": ["number sense", "shape and space", "patterns"],
        "app_use": "bridge tags from play evidence to primary maths readiness",
        "source_ids": ["edb-kindergarten-overview"],
    },
    {
        "id": "kg-nature-living",
        "name": "Nature and Living",
        "display_name_zh": "大自然與生活",
        "kla_id": "kindergarten",
        "kla_name": "Kindergarten Learning Areas",
        "stage_ids": ["kg"],
        "grades": ["K1", "K2", "K3"],
        "strands": ["observation", "everyday inquiry", "living environment"],
        "app_use": "portfolio inquiry evidence and activity tagging",
        "source_ids": ["edb-kindergarten-overview"],
    },
    {
        "id": "kg-self-society",
        "name": "Self and Society",
        "display_name_zh": "個人與群體",
        "kla_id": "kindergarten",
        "kla_name": "Kindergarten Learning Areas",
        "stage_ids": ["kg"],
        "grades": ["K1", "K2", "K3"],
        "strands": ["self-care", "social skills", "values and attitudes"],
        "app_use": "self-care and social development portfolio sections",
        "source_ids": ["edb-kindergarten-overview"],
    },
    {
        "id": "kg-arts-creativity",
        "name": "Arts and Creativity",
        "display_name_zh": "藝術與創意",
        "kla_id": "kindergarten",
        "kla_name": "Kindergarten Learning Areas",
        "stage_ids": ["kg"],
        "grades": ["K1", "K2", "K3"],
        "strands": ["visual expression", "music", "creative play"],
        "app_use": "artwork uploads, creativity tags, and interview portfolio evidence",
        "source_ids": ["edb-kindergarten-overview"],
    },
    {
        "id": "chinese-language",
        "name": "Chinese Language",
        "display_name_zh": "中國語文",
        "kla_id": "chinese-language",
        "kla_name": "Chinese Language Education",
        "stage_ids": ["p1-p6", "s1-s3", "s4-s6"],
        "grades": ["P1", "P2", "P3", "P4", "P5", "P6", "S1", "S2", "S3", "S4", "S5", "S6"],
        "strands": ["reading", "writing", "listening", "speaking", "literature and culture"],
        "app_use": "future OCR review for reading comprehension, composition, dictation, and writing evidence",
        "source_ids": ["edb-kla-overview-2526", "edb-chinese-docs"],
    },
    {
        "id": "putonghua",
        "name": "Putonghua",
        "display_name_zh": "普通話",
        "kla_id": "chinese-language",
        "kla_name": "Chinese Language Education",
        "stage_ids": ["p1-p6", "s1-s3"],
        "grades": ["P1", "P2", "P3", "P4", "P5", "P6", "S1", "S2", "S3"],
        "strands": ["listening", "speaking", "phonetics", "communication"],
        "app_use": "oral practice records and language profile tags",
        "source_ids": ["edb-kla-overview-2526", "edb-chinese-docs"],
    },
    {
        "id": "chinese-literature",
        "name": "Chinese Literature",
        "display_name_zh": "中國文學",
        "kla_id": "chinese-language",
        "kla_name": "Chinese Language Education",
        "stage_ids": ["s4-s6"],
        "grades": ["S4", "S5", "S6"],
        "strands": ["literary appreciation", "critical response", "culture"],
        "app_use": "senior secondary reading log and analysis evidence",
        "source_ids": ["edb-kla-overview-2526", "edb-chinese-docs"],
    },
    {
        "id": "english-language",
        "name": "English Language",
        "display_name_zh": "英國語文",
        "kla_id": "english-language",
        "kla_name": "English Language Education",
        "stage_ids": ["p1-p6", "s1-s3", "s4-s6"],
        "grades": ["P1", "P2", "P3", "P4", "P5", "P6", "S1", "S2", "S3", "S4", "S5", "S6"],
        "strands": ["interpersonal", "knowledge", "experience", "reading", "writing", "speaking"],
        "app_use": "future English homework review, writing feedback, vocabulary and reading plans",
        "source_ids": ["edb-kla-overview-2526", "edb-english-docs"],
    },
    {
        "id": "literature-in-english",
        "name": "Literature in English",
        "display_name_zh": "英語文學",
        "kla_id": "english-language",
        "kla_name": "English Language Education",
        "stage_ids": ["s4-s6"],
        "grades": ["S4", "S5", "S6"],
        "strands": ["poetry", "prose", "drama", "critical appreciation"],
        "app_use": "senior secondary literary response evidence and practice prompts",
        "source_ids": ["edb-kla-overview-2526", "edb-english-docs"],
    },
    {
        "id": "mathematics",
        "name": "Mathematics",
        "display_name_zh": "數學",
        "kla_id": "mathematics",
        "kla_name": "Mathematics Education",
        "stage_ids": ["p1-p6", "s1-s3", "s4-s6"],
        "grades": ["P1", "P2", "P3", "P4", "P5", "P6", "S1", "S2", "S3", "S4", "S5", "S6"],
        "strands": ["number", "measure", "shape and space", "data handling", "algebra"],
        "app_use": "current OCR review, weakness tracking, and personalised practice generation",
        "source_ids": ["edb-kla-overview-2526", "edb-mathematics-docs"],
    },
    {
        "id": "primary-science",
        "name": "Primary Science",
        "display_name_zh": "小學科學",
        "kla_id": "science",
        "kla_name": "Science Education",
        "stage_ids": ["p1-p6"],
        "grades": ["P1", "P4"],
        "strands": ["scientific inquiry", "life and environment", "energy and change", "STEAM"],
        "app_use": "science observation uploads and inquiry portfolio evidence",
        "source_ids": ["edb-kla-overview-2526", "edb-science-docs"],
        "status": "2025/26 starts at P1 and P4; extends to all primary levels by 2027/28.",
    },
    {
        "id": "science",
        "name": "Science",
        "display_name_zh": "科學",
        "kla_id": "science",
        "kla_name": "Science Education",
        "stage_ids": ["s1-s3"],
        "grades": ["S1", "S2", "S3"],
        "strands": ["scientific investigation", "STSE", "life and living", "matter", "energy"],
        "app_use": "junior secondary science mapping and concept diagnosis",
        "source_ids": ["edb-kla-overview-2526", "edb-science-docs"],
    },
    {
        "id": "biology",
        "name": "Biology",
        "display_name_zh": "生物",
        "kla_id": "science",
        "kla_name": "Science Education",
        "stage_ids": ["s4-s6"],
        "grades": ["S4", "S5", "S6"],
        "strands": ["cells and molecules", "organisms", "genetics", "ecology"],
        "app_use": "senior secondary concept map and lab evidence tags",
        "source_ids": ["edb-kla-overview-2526", "edb-science-docs"],
    },
    {
        "id": "chemistry",
        "name": "Chemistry",
        "display_name_zh": "化學",
        "kla_id": "science",
        "kla_name": "Science Education",
        "stage_ids": ["s4-s6"],
        "grades": ["S4", "S5", "S6"],
        "strands": ["atomic world", "materials", "reactions", "quantitative chemistry"],
        "app_use": "senior secondary problem tagging and lab-skill evidence",
        "source_ids": ["edb-kla-overview-2526", "edb-science-docs"],
    },
    {
        "id": "physics",
        "name": "Physics",
        "display_name_zh": "物理",
        "kla_id": "science",
        "kla_name": "Science Education",
        "stage_ids": ["s4-s6"],
        "grades": ["S4", "S5", "S6"],
        "strands": ["mechanics", "electricity", "waves", "energy"],
        "app_use": "senior secondary quantitative practice and misconception tags",
        "source_ids": ["edb-kla-overview-2526", "edb-science-docs"],
    },
    {
        "id": "general-studies",
        "name": "General Studies",
        "display_name_zh": "常識",
        "kla_id": "cross-curricular",
        "kla_name": "Cross-KLA / Transition",
        "stage_ids": ["p1-p6"],
        "grades": ["P2", "P3", "P5", "P6"],
        "strands": ["personal and social", "science and technology", "community", "health"],
        "app_use": "legacy primary uploads during transition to Primary Science and Humanities",
        "source_ids": ["edb-kla-overview-2526", "edb-primary-guide-2024"],
        "status": "Progressively replaced by Primary Science and Primary Humanities from 2025/26.",
    },
    {
        "id": "primary-humanities",
        "name": "Primary Humanities",
        "display_name_zh": "小學人文",
        "kla_id": "pshe",
        "kla_name": "Personal, Social and Humanities Education",
        "stage_ids": ["p1-p6"],
        "grades": ["P1", "P4"],
        "strands": ["self and society", "country and culture", "community", "global awareness"],
        "app_use": "values, culture, and humanities evidence in learning passport",
        "source_ids": ["edb-kla-overview-2526", "edb-pshe-docs"],
        "status": "2025/26 starts at P1 and P4; extends to all primary levels by 2027/28.",
    },
    {
        "id": "technology-education",
        "name": "Technology Education",
        "display_name_zh": "科技教育",
        "kla_id": "technology",
        "kla_name": "Technology Education",
        "stage_ids": ["p1-p6", "s1-s3"],
        "grades": ["P1", "P4", "S1", "S2", "S3"],
        "strands": ["ICT", "materials and structures", "systems and control", "technology and living"],
        "app_use": "coding, AI literacy, and STEAM activity tags",
        "source_ids": ["edb-kla-overview-2526", "edb-technology-docs"],
        "status": "Primary is modular; junior secondary includes AI learning module from 2023/24.",
    },
    {
        "id": "business-accounting-financial-studies",
        "name": "Business, Accounting and Financial Studies",
        "display_name_zh": "企業、會計與財務概論",
        "kla_id": "technology",
        "kla_name": "Technology Education",
        "stage_ids": ["s4-s6"],
        "grades": ["S4", "S5", "S6"],
        "strands": ["business environment", "accounting", "financial management"],
        "app_use": "senior secondary business concept and case-study tracking",
        "source_ids": ["edb-kla-overview-2526", "edb-technology-docs"],
    },
    {
        "id": "design-and-applied-technology",
        "name": "Design and Applied Technology",
        "display_name_zh": "設計與應用科技",
        "kla_id": "technology",
        "kla_name": "Technology Education",
        "stage_ids": ["s4-s6"],
        "grades": ["S4", "S5", "S6"],
        "strands": ["design process", "materials", "systems", "technology application"],
        "app_use": "project portfolio evidence and design process reflections",
        "source_ids": ["edb-kla-overview-2526", "edb-technology-docs"],
    },
    {
        "id": "health-management-social-care",
        "name": "Health Management and Social Care",
        "display_name_zh": "健康管理與社會關懷",
        "kla_id": "technology",
        "kla_name": "Technology Education",
        "stage_ids": ["s4-s6"],
        "grades": ["S4", "S5", "S6"],
        "strands": ["health", "social care", "community services"],
        "app_use": "senior secondary case-study and reflection evidence",
        "source_ids": ["edb-kla-overview-2526", "edb-technology-docs"],
    },
    {
        "id": "information-communication-technology",
        "name": "Information and Communication Technology",
        "display_name_zh": "資訊及通訊科技",
        "kla_id": "technology",
        "kla_name": "Technology Education",
        "stage_ids": ["s4-s6"],
        "grades": ["S4", "S5", "S6"],
        "strands": ["data", "programming", "networks", "systems", "social implications"],
        "app_use": "programming practice, project evidence, and digital literacy tracking",
        "source_ids": ["edb-kla-overview-2526", "edb-technology-docs"],
    },
    {
        "id": "technology-and-living",
        "name": "Technology and Living",
        "display_name_zh": "科技與生活",
        "kla_id": "technology",
        "kla_name": "Technology Education",
        "stage_ids": ["s4-s6"],
        "grades": ["S4", "S5", "S6"],
        "strands": ["food science", "fashion and textiles", "family living", "resource management"],
        "app_use": "practical project evidence and applied knowledge tags",
        "source_ids": ["edb-kla-overview-2526", "edb-technology-docs"],
    },
    {
        "id": "chinese-history",
        "name": "Chinese History",
        "display_name_zh": "中國歷史",
        "kla_id": "pshe",
        "kla_name": "Personal, Social and Humanities Education",
        "stage_ids": ["s1-s3", "s4-s6"],
        "grades": ["S1", "S2", "S3", "S4", "S5", "S6"],
        "strands": ["chronology", "historical sources", "culture", "national development"],
        "app_use": "history source analysis and timeline revision evidence",
        "source_ids": ["edb-kla-overview-2526", "edb-pshe-docs"],
        "status": "Independent compulsory subject at junior secondary level.",
    },
    {
        "id": "citizenship-economics-society",
        "name": "Citizenship, Economics and Society",
        "display_name_zh": "公民、經濟與社會",
        "kla_id": "pshe",
        "kla_name": "Personal, Social and Humanities Education",
        "stage_ids": ["s1-s3"],
        "grades": ["S1", "S2", "S3"],
        "strands": ["citizenship", "economics", "society", "personal finance"],
        "app_use": "junior secondary issue analysis and concept mapping",
        "source_ids": ["edb-kla-overview-2526", "edb-pshe-docs"],
        "status": "Implemented at S1 in 2024/25 and extends to all junior secondary levels by 2026/27.",
    },
    {
        "id": "geography",
        "name": "Geography",
        "display_name_zh": "地理",
        "kla_id": "pshe",
        "kla_name": "Personal, Social and Humanities Education",
        "stage_ids": ["s1-s3", "s4-s6"],
        "grades": ["S1", "S2", "S3", "S4", "S5", "S6"],
        "strands": ["place and space", "human-environment interaction", "data skills", "sustainability"],
        "app_use": "map skills, data interpretation, and issue inquiry tags",
        "source_ids": ["edb-kla-overview-2526", "edb-pshe-docs"],
    },
    {
        "id": "history",
        "name": "History",
        "display_name_zh": "歷史",
        "kla_id": "pshe",
        "kla_name": "Personal, Social and Humanities Education",
        "stage_ids": ["s1-s3", "s4-s6"],
        "grades": ["S1", "S2", "S3", "S4", "S5", "S6"],
        "strands": ["historical enquiry", "sources", "change and continuity", "perspectives"],
        "app_use": "source-based question review and revision planning",
        "source_ids": ["edb-kla-overview-2526", "edb-pshe-docs"],
    },
    {
        "id": "religious-education",
        "name": "Religious Education",
        "display_name_zh": "宗教教育",
        "kla_id": "pshe",
        "kla_name": "Personal, Social and Humanities Education",
        "stage_ids": ["s1-s3"],
        "grades": ["S1", "S2", "S3"],
        "strands": ["beliefs", "values", "ethics", "reflection"],
        "app_use": "values reflection and school-based subject tags",
        "source_ids": ["edb-kla-overview-2526", "edb-pshe-docs"],
    },
    {
        "id": "economics",
        "name": "Economics",
        "display_name_zh": "經濟",
        "kla_id": "pshe",
        "kla_name": "Personal, Social and Humanities Education",
        "stage_ids": ["s4-s6"],
        "grades": ["S4", "S5", "S6"],
        "strands": ["scarcity", "markets", "macroeconomy", "policy"],
        "app_use": "concept questions, graph interpretation, and case evidence",
        "source_ids": ["edb-kla-overview-2526", "edb-pshe-docs"],
    },
    {
        "id": "ethics-and-religious-studies",
        "name": "Ethics and Religious Studies",
        "display_name_zh": "倫理與宗教",
        "kla_id": "pshe",
        "kla_name": "Personal, Social and Humanities Education",
        "stage_ids": ["s4-s6"],
        "grades": ["S4", "S5", "S6"],
        "strands": ["ethics", "religion", "values", "argumentation"],
        "app_use": "essay planning and reflective portfolio evidence",
        "source_ids": ["edb-kla-overview-2526", "edb-pshe-docs"],
    },
    {
        "id": "tourism-and-hospitality-studies",
        "name": "Tourism and Hospitality Studies",
        "display_name_zh": "旅遊與款待",
        "kla_id": "pshe",
        "kla_name": "Personal, Social and Humanities Education",
        "stage_ids": ["s4-s6"],
        "grades": ["S4", "S5", "S6"],
        "strands": ["tourism industry", "hospitality", "destination management", "customer service"],
        "app_use": "case-study practice and vocational interest profile",
        "source_ids": ["edb-kla-overview-2526", "edb-pshe-docs"],
    },
    {
        "id": "citizenship-social-development",
        "name": "Citizenship and Social Development",
        "display_name_zh": "公民與社會發展",
        "kla_id": "cross-curricular",
        "kla_name": "Senior Secondary Core",
        "stage_ids": ["s4-s6"],
        "grades": ["S4", "S5", "S6"],
        "strands": ["Hong Kong under One Country Two Systems", "country and world", "contemporary issues"],
        "app_use": "senior secondary issue inquiry and source evidence tracking",
        "source_ids": ["edb-kla-overview-2526", "edb-csd-docs"],
    },
    {
        "id": "music",
        "name": "Music",
        "display_name_zh": "音樂",
        "kla_id": "arts",
        "kla_name": "Arts Education",
        "stage_ids": ["p1-p6", "s1-s3", "s4-s6"],
        "grades": ["P1", "P2", "P3", "P4", "P5", "P6", "S1", "S2", "S3", "S4", "S5", "S6"],
        "strands": ["performing", "creating", "listening", "music in context"],
        "app_use": "portfolio performance evidence and arts participation tags",
        "source_ids": ["edb-kla-overview-2526", "edb-arts-docs"],
    },
    {
        "id": "visual-arts",
        "name": "Visual Arts",
        "display_name_zh": "視覺藝術",
        "kla_id": "arts",
        "kla_name": "Arts Education",
        "stage_ids": ["p1-p6", "s1-s3", "s4-s6"],
        "grades": ["P1", "P2", "P3", "P4", "P5", "P6", "S1", "S2", "S3", "S4", "S5", "S6"],
        "strands": ["creating", "appreciating", "visual culture", "arts in context"],
        "app_use": "artwork upload, portfolio curation, and visual response tags",
        "source_ids": ["edb-kla-overview-2526", "edb-arts-docs"],
    },
    {
        "id": "physical-education",
        "name": "Physical Education",
        "display_name_zh": "體育",
        "kla_id": "physical-education",
        "kla_name": "Physical Education",
        "stage_ids": ["p1-p6", "s1-s3", "s4-s6"],
        "grades": ["P1", "P2", "P3", "P4", "P5", "P6", "S1", "S2", "S3", "S4", "S5", "S6"],
        "strands": ["motor skills", "health and fitness", "sports knowledge", "values and attitudes"],
        "app_use": "whole-person dashboard, activity records, and health habit evidence",
        "source_ids": ["edb-kla-overview-2526", "edb-pe-docs"],
    },
    {
        "id": "applied-learning",
        "name": "Applied Learning",
        "display_name_zh": "應用學習",
        "kla_id": "cross-curricular",
        "kla_name": "Senior Secondary Elective Pathways",
        "stage_ids": ["s4-s6"],
        "grades": ["S4", "S5", "S6"],
        "strands": [
            "creative studies",
            "media and communication",
            "business management and law",
            "services",
            "applied science",
            "engineering and production",
        ],
        "app_use": "senior secondary pathway planning and portfolio evidence",
        "source_ids": ["edb-kla-overview-2526"],
    },
    {
        "id": "other-languages",
        "name": "Other Languages",
        "display_name_zh": "其他語言",
        "kla_id": "cross-curricular",
        "kla_name": "Senior Secondary Elective Pathways",
        "stage_ids": ["s4-s6"],
        "grades": ["S4", "S5", "S6"],
        "strands": ["French", "German", "Hindi", "Japanese", "Korean", "Spanish", "Urdu"],
        "app_use": "language profile and elective pathway planning",
        "source_ids": ["edb-kla-overview-2526"],
        "status": "Hindi is listed for S4 in the 2025/26 subject overview; S5-S6 list six other languages.",
    },
]


def get_curriculum_catalog() -> dict[str, Any]:
    return {
        "ok": True,
        "jurisdiction": "Hong Kong",
        "school_year": "2025/26",
        "sources": CURRICULUM_SOURCES,
        "stages": CURRICULUM_STAGES,
        "subjects": CURRICULUM_SUBJECTS,
    }


def subjects_for_grade(grade: str) -> list[dict[str, Any]]:
    normalized = grade.strip().upper()
    return [subject for subject in CURRICULUM_SUBJECTS if normalized in subject["grades"]]


def find_subject_for_grade(grade: str, subject_name: str) -> dict[str, Any] | None:
    normalized_subject = subject_name.strip().lower()
    for subject in subjects_for_grade(grade):
        names = {
            subject["id"].lower(),
            subject["name"].lower(),
            subject["display_name_zh"].lower(),
        }
        if normalized_subject in names:
            return subject
    return None


def subject_names_for_grade(grade: str) -> list[str]:
    return [subject["name"] for subject in subjects_for_grade(grade)]
